labelDict = {
    "electricityLink1_2": "elLink",
    "electricityLink1_3": "elLink",
    "electricityLink1_4": "elLink",
    "electricityLink2_3": "elLink",
    "electricityLink2_4": "elLink",
    "electricityLink3_4": "elLink",
    "electricityLink2_1": "elLink",
    "electricityLink3_2": "elLink",
    "electricityLink3_1": "elLink",
    "electricityLink4_3": "elLink",
    "electricityLink4_2": "elLink",
    "electricityLink4_1": "elLink",
    "naturalGasResource__Building1": "natGas_B1",
    "naturalGasBus__Building1": "natGas_B1",
    "gridBus__Building1": "grid_B1",
    "pv__Building1": "pv_B1",
    "electricityResource__Building1":"grid_B1",
    "gridElectricity__Building1": "grid_B1",
    "CHP_SH__Building1": "CHP_SH_B1",
    "CHP_DHW__Building1": "CHP_DHW_B1",
    "electricityBus__Building1": "prodEl_B1",
    "producedElectricity__Building1": "prodEl_B1",
    "electricalStorage__Building1": "Bat_B1",
    "excesselectricityBus__Building1": "exEl_B1",
    "electricityInBus__Building1": "usedEl_B1",
    "HP_SH__Building1": "HP_SH_B1",
    "HP_DHW__Building1": "HP_DHW_B1",
    "solarCollector__Building1": "solar_B1",
    "spaceHeatingBus__Building1": "SH_B1",
    "spaceHeating__Building1": "Q_sh_B1",
    "shStorage__Building1": "shStor_B1",
    "spaceHeatingDemandBus__Building1": "Q_sh_B1",
    "dhwStorageBus__Building1": "dhwStor_B1",
    "dhwStorage__Building1": "dhwStor_B1",
    "domesticHotWaterBus__Building1": "Q_dhw_B1",
    "electricityDemand__Building1": "Q_el_B1",
    "spaceHeatingDemand__Building1": "Q_sh_B1",
    "domesticHotWaterDemand__Building1": "Q_dhw_B1",

    "naturalGasResource__Building2": "natGas_B2",
    "naturalGasBus__Building2": "natGas_B2",
    "electricityResource__Building2": "grid_B2",
    "gridBus__Building2": "grid_B2",
    "pv__Building2": "pv_B2",
    "gridElectricity__Building2": "grid_B2",
    "CHP_SH__Building2": "CHP_SH_B2",
    "CHP_DHW__Building2": "CHP_DHW_B2",
    "electricityBus__Building2": "prodEl_B2",
    "producedElectricity__Building2": "prodEl_B2",
    "electricalStorage__Building2": "Bat_B2",
    "excesselectricityBus__Building2": "exEl_B2",
    "electricityInBus__Building2": "usedEl_B2",
    "HP_SH__Building2": "HP_SH_B2",
    "HP_DHW__Building2": "HP_DHW_B2",
    "solarCollector__Building2": "solar_B2",
    "spaceHeatingBus__Building2": "SH_B2",
    "spaceHeating__Building2": "Q_sh_B2",
    "shStorage__Building2": "shStor_B2",
    "spaceHeatingDemandBus__Building2": "Q_sh_B2",
    "dhwStorageBus__Building2": "dhwStor_B2",
    "dhwStorage__Building2": "dhwStor_B2",
    "domesticHotWaterBus__Building2": "Q_dhw_B2",
    "electricityDemand__Building2": "Q_el_B2",
    "spaceHeatingDemand__Building2":        "Q_sh_B2",
    "domesticHotWaterDemand__Building2": "Q_dhw_B2",

    "naturalGasResource__Building3": "natGas_B3",
    "naturalGasBus__Building3": "natGas_B3",
    "electricityResource__Building3": "grid_B3",
    "gridBus__Building3": "grid_B3",
    "pv__Building3": "pv_B3",
    "gridElectricity__Building3": "grid_B3",
    "CHP_SH__Building3": "CHP_SH_B3",
    "CHP_DHW__Building3": "CHP_DHW_B3",
    "electricityBus__Building3": "prodEl_B3",
    "producedElectricity__Building3": "prodEl_B3",
    "electricalStorage__Building3": "Bat_B3",
    "excesselectricityBus__Building3": "exEl_B3",
    "electricityInBus__Building3": "usedEl_B3",
    "HP_SH__Building3": "HP_SH_B3",
    "HP_DHW__Building3": "HP_DHW_B3",
    "solarCollector__Building3": "solar_B3",
    "spaceHeatingBus__Building3": "SH_B3",
    "spaceHeating__Building3": "Q_sh_B3",
    "shStorage__Building3": "shStor_B3",
    "spaceHeatingDemandBus__Building3": "Q_sh_B3",
    "dhwStorageBus__Building3": "dhwStor_B3",
    "dhwStorage__Building3": "dhwStor_B3",
    "domesticHotWaterBus__Building3": "Q_dhw_B3",
    "electricityDemand__Building3": "Q_el_B3",
    "spaceHeatingDemand__Building3":        "Q_sh_B3",
    "domesticHotWaterDemand__Building3": "Q_dhw_B3",

    "naturalGasResource__Building4": "natGas_B4",
    "naturalGasBus__Building4": "natGas_B4",
    "electricityResource__Building4": "grid_B4",
    "gridBus__Building4": "grid_B4",
    "pv__Building4": "pv_B4",
    "gridElectricity__Building4": "grid_B4",
    "CHP_SH__Building4": "CHP_SH_B4",
    "CHP_DHW__Building4": "CHP_DHW_B4",
    "electricityBus__Building4": "prodEl_B4",
    "producedElectricity__Building4": "prodEl_B4",
    "electricalStorage__Building4": "Bat_B4",
    "excesselectricityBus__Building4": "exEl_B4",
    "electricityInBus__Building4": "usedEl_B4",
    "HP_SH__Building4": "HP_SH_B4",
    "HP_DHW__Building4": "HP_DHW_B4",
    "solarCollector__Building4": "solar_B4",
    "spaceHeatingBus__Building4": "SH_B4",
    "spaceHeating__Building4": "Q_sh_B4",
    "shStorage__Building4": "shStor_B4",
    "spaceHeatingDemandBus__Building4": "Q_sh_B4",
    "dhwStorageBus__Building4": "dhwStor_B4",
    "dhwStorage__Building4": "dhwStor_B4",
    "domesticHotWaterBus__Building4": "Q_dhw_B4",
    "electricityDemand__Building4": "Q_el_B4",
    "spaceHeatingDemand__Building4":        "Q_sh_B4",
    "domesticHotWaterDemand__Building4": "Q_dhw_B4",
}

labelPositionDict={
    "natGas":	[0.001, 0.65],
    "grid":	[0.001, 0.15],
    "pv":   [0.001, 0.3],
    "CHP_SH":	[0.1, 0.6],
    "CHP_DHW":	[0.1, 0.85],
    "prodEl":	[0.2, 0.3],
    "elLink":	[0.3, 0.35],
	"Bat":	[0.3, 0.25],
    "usedEl":	[0.5, 0.2],
    "HP_SH":	[0.6, 0.4],
    "HP_DHW":	[0.6, 0.85],
    "solar":	[0.6, 0.85],
    "SH":	[0.7, 0.58],
    "shStor":	[0.8, 0.37],
    "dhwStor":	[0.8, 0.85],
    "exEl": [0.999, 0.25],
    "Q_el":	[0.999, 0.15],
    "Q_sh":	[0.999, 0.6],
    "Q_dhw":	[0.999, 0.85]
	}